project:
  type: website

website:
  title: "David K. Amakye"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog/
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
        href: cv.qmd
        text: CV
    right:
      - icon: github
        href: "https://github.com/RealKingDavid"
      - icon: envelope
        href: mailto:amakyekojodavid@gmail.com
      - icon: linkedin
        aria-label: "LinkedIn"
        href: https://linkedin.com/in/david-amakye
      - icon: wordpress
        aria-label: "WordPress Blog"
        href: https://amakye.wordpress.com
format:
  html:
    theme: cosmo
    css: resources/styles.css
    toc: true
